version: "3.3"

x-proxy-common: &proxy-common
  # user: root
  # command: tail -f /dev/null
  volumes: 
    - ./etc/:/etc/nginx/conf.d
    # - ./modules:/home/openresty/modules

services:
  openresty:
    <<: *proxy-common
    container_name: openresty
    ports:
      - 80:80
    build:
      dockerfile: Dockerfile
      target: openresty
    networks:
      - external-net

networks:
  external-net:
    name: external-net
    external: true
