version: "3.3"

services:
  proxy:
    container_name: proxy
    ports:
      - 8001:8001
    build:
      dockerfile: Dockerfile
      target: openresty
    volumes: 
      - ./etc/proxy.conf:/etc/nginx/conf.d/default.conf
    networks:
      - external-net

  cache:
    container_name: cache
    ports:
      - 80:80
    build:
      dockerfile: Dockerfile
      target: openresty
    volumes: 
      - ./etc/cache-server.conf:/etc/nginx/conf.d/default.conf
    networks:
      - external-net

networks:
  external-net:
    name: external-net
    external: true
