version: "3.3"

services:
  # proxy:
  #   container_name: proxy
  #   ports:
  #     - 8001:8001
  #   build:
  #     dockerfile: Dockerfile
  #     target: openresty
  #   volumes: 
  #     - ./etc/proxy.conf:/etc/nginx/conf.d/default.conf
  #   networks:
  #     - external-net

  cache1:
    container_name: cache1
    user: root
    ports:
      - 80:80
    expose:
      - "9000"
    build:
      dockerfile: Dockerfile
      target: openresty
    volumes: 
      - ./etc/cache-server-mem.conf:/etc/nginx/conf.d/default.conf
    networks:
      - external-net
  cache2:
    container_name: cache2
    user: root
    ports:
      - 81:80
    expose:
      - "9000"
    build:
      dockerfile: Dockerfile
      target: openresty
    volumes: 
      - ./etc/cache-server-mem.conf:/etc/nginx/conf.d/default.conf
    networks:
      - external-net
  cache3:
    user: root
    container_name: cache3
    ports:
      - 82:80
    expose:
      - "9000"
    build:
      dockerfile: Dockerfile
      target: openresty
    volumes: 
      - ./etc/cache-server-mem.conf:/etc/nginx/conf.d/default.conf
    networks:
      - external-net

networks:
  external-net:
    name: external-net
    external: true
